sudo: required

language: c

services:
    - docker

env:
    - DOCKER_IMAGE_VERSION=2

script:
    - ./m4-preprocess.sh
    - ./docker-build.sh centos6-lts-a
    - ./docker-build.sh centos6-lts-b
    - ./deploy.sh
