sudo: required

language: c

services:
    - docker

env:
    - DOCKER_IMAGE_VERSION=2

script:
    - ./m4-preprocess.sh
    - ./docker-build.sh centos6-lts-a
    - ./docker-build.sh centos6-lts-b

deploy:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push lancelet/centos6-lts-a:$DOCKER_IMAGE_VERSION
    - docker push lancelet/centos6-lts-b:$DOCKER_IMAGE_VERSION
