sudo: required

env:
    global:
        - DOCKER_IMAGE_VERSION=3
        - STACK_PROJECTDIR=/opt/stack
        # STACK_WORKDIR has to be relative for now, due to this issue:
        #   https://github.com/commercialhaskell/stack/issues/1731
        # - STACK_WORKDIR=$STACK_PROJECTDIR/.stack-work
        - STACK_WORKDIR=./.stack-work
        - STACK_YAML=$STACK_PROJECTDIR/stack.yaml
        - STACK_SETUP="stack setup --no-terminal"
        - STACK_INSTALL="stack install --no-terminal --executable-profiling --work-dir $STACK_WORKDIR --stack-yaml $STACK_YAML"

matrix:
    include:
        - env: image=centos6-lts-a
          services: docker
          language: c
        - env: image=centos6-lts-b
          services: docker
          language: c
        - env: image=centos6-lts-c
          services: docker
          language: c
        - env: image=centos6-lts-d
          services: docker
          language: c

before_script:
    - ./m4-preprocess.sh

script:
    - ./docker-build.sh $image

after_script:
    - ./deploy.sh $image
