sudo: required

language: c

services:
    global:
        - docker

env:
    global:
        - DOCKER_IMAGE_VERSION=2
        - STACK_WORKDIR=/opt/stack
        - STACK_SETUP="stack setup --no-terminal"
        - STACK_INSTALL="stack install --no-terminal --executable-profiling"

matrix:
    include:
        - env: image=centos6-lts-a
        - env: image=centos6-lts-b
        - env: image=centos6-lts-c
        - env: image=centos6-lts-d

before_script:
    - ./m4-preprocess.sh

script:
    - ./docker-build.sh $image

after_script:
    - ./deploy.sh

