sudo: required

language: c

services:
    - docker

env:
    - image=centos6-lts-a
    - image=centos6-lts-b
    - image=centos6-lts-c
    - image=centos6-lts-d
    global:
        - DOCKER_IMAGE_VERSION=2
        - STACK_WORKDIR=/opt/stack
        - STACK_SETUP="stack setup --no-terminal"
        - STACK_INSTALL="stack install --no-terminal --executable-profiling"

before_script:
    - ./m4-preprocess.sh

script:
    - ./docker-build.sh $image

after_script:
    - ./deploy.sh

