sudo: required

language: c

services:
    - docker

env:
    - DOCKER_IMAGE_VERSION=2
    - STACK_WORKDIR=/opt/stack
    - STACK_SETUP=stack setup --no-terminal
    - STACK_INSTALL=stack install --no-terminal --executable-profiling

script:
    - ./m4-preprocess.sh
    - ./docker-build.sh centos6-lts-a
    - ./docker-build.sh centos6-lts-b
    - ./docker-build.sh centos6-lts-c
    - ./docker-build.sh centos6-lts-d
    - ./deploy.sh
