sudo: required

env:
    global:
        - DOCKER_IMAGE_VERSION=2
        - STACK_WORKDIR=/opt/stack
        - STACK_SETUP="stack setup --no-terminal"
        - STACK_INSTALL="stack install --no-terminal --executable-profiling"

matrix:
    include:
        - env: image=centos6-lts-a
          services: docker
          language: c
        - env: image=centos6-lts-b
          services: docker
          language: c
        - env: image=centos6-lts-c
          services: docker
          language: c
        - env: image=centos6-lts-d
          services: docker
          language: c

before_script:
    - ./m4-preprocess.sh

script:
    - travis_wait 30 ./docker-build.sh $image

after_script:
    - ./deploy.sh $image
