flags: {}
packages:
- '.'
extra-deps:
- control-monad-omega-0.3.1
- servant-0.5
- servant-blaze-0.5
- servant-cassava-0.5
- servant-client-0.5
- servant-docs-0.5
- servant-server-0.5
resolver: lts-5.12
